import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import ResultsDashboard from './ResultsDashboard';
import SEO from './SEO';
import { sampleReportData } from '../sampleData';

export default function SampleReportView() {
  const navigate = useNavigate();

  const handleReset = () => {
    navigate(-1);
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col">
      <SEO
        title="Sample Report | Lumera"
        description="Preview our AI-powered visa refusal analysis report. See how we analyze refusal letters, generate appeal strategies, and build embassy-ready document checklists."
      />
      <div className="bg-indigo-600 border-b border-indigo-500 py-4 px-6 flex flex-col items-center justify-center text-center text-white">
        <h1 className="text-xl font-bold tracking-widest mb-1">SAMPLE REPORT</h1>
        <p className="text-sm font-medium text-indigo-100">This is an example of the report structure and recommendations generated by Lumera.</p>
      </div>
      <div className="flex-1 pb-24">
        <ResultsDashboard result={sampleReportData} onReset={handleReset} isSample={true} purchasedPlan="premium" />
      </div>
    </div>
  );
}
