import React from 'react';
import { useNavigate, Link } from 'react-router-dom';
import ResultsDashboard from './ResultsDashboard';
import { sampleReportData } from '../sampleData';

export default function SampleReportView() {
  const navigate = useNavigate();

  const handleReset = () => {
    navigate(-1);
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col">
      <div className="bg-indigo-600 border-b border-indigo-500 py-4 px-6 flex flex-col items-center justify-center text-center text-white">
        <h1 className="text-xl font-bold tracking-widest mb-1">SAMPLE REPORT</h1>
        <p className="text-sm font-medium text-indigo-100">This is an example of the report structure and recommendations generated by Visa Appeal.</p>
      </div>
      <div className="flex-1 pb-24">
        <ResultsDashboard result={sampleReportData} onReset={handleReset} isSample={true} purchasedPlan="premium" />
        <div className="max-w-5xl mx-auto px-4 sm:px-6 w-full text-center mt-12 pb-12">
          <Link to="/flow" className="inline-block bg-white text-zinc-950 px-10 py-5 rounded-full font-bold text-lg hover:bg-zinc-200 transition-colors shadow-xl shadow-white/10 hover:scale-105">
            Generate My Appeal Package
          </Link>
        </div>
      </div>
    </div>
  );
}
